### PR TITLE
Add OctoPrint icon

### PR DESCRIPTION
**Pull request by crysxd**
Super simple icon, hope all is good! 

Amazing project!

### CODE REVIEW

**Comment by loukjltd** [comment]
Hi there, it seems that you didn't submit high-res & low-res png files, or your icons won't be shown on the website. Just add your png files to the specific directory. That'll will help the Administrator a lot.

Thanks!

**Comment by crysxd** [comment]
I added the missing PNGs! As a feedback, the PNGs for the webpages where missing from the instructions in the Figma template :)

**Comment by elrumo** [comment]
@loukjltd thanks for helping! 😁
@crysxd

**Comment by crysxd** [comment]
No worries , I know how time consuming this stuff can get :)  Your work is highly appreciated!

**Pull request merged**
