### PR TITLE
added two steam replacement icons

### PR DESCRIPTION
**Pull request by Asdkjf13**

### CODE REVIEW

**Comment by elrumo** [comment]
Could you add the low-res and high-res png so I could merge the pull request? Thanks!

**Comment by Asdkjf13** [comment]
Sure. Could you tell me where to add them? I’m not really familiar with GitHub. Sorry for your inconvenience.

**Comment by elrumo** [comment]
No worries! I've been trying to think of an alternative for people that are not as familiar with GitHub. In the meantime, you could just upload them to a shared folder on Google Drive, OneDrive or something like that and I'll add them for you.

**Comment by Asdkjf13** [comment]
Thanks for the help. Here’s the dropbox link. Let me know if anything’s wrong:)

https://www.dropbox.com/sh/kp3ouuphtcuuike/AADnenY5ZtX-S3wM2vhGljU0a?dl=0

**Comment by elrumo** [comment]
Awesome, thanks!

**Pull request merged**
