### PR TITLE
Adds a couple of lesser known apps, 'Boop' and 'Flow'.

### PR DESCRIPTION
**Pull request by Leavever**

### CODE REVIEW

**Comment by elrumo** [comment]
Could you please add the low res (256px) and high res .pngs please? or else the preview won't display on the website. Thanks!

**Comment by Leavever** [comment]
> Could you please add the low res (256px) and high res .pngs please? or else the preview won't display on the website. Thanks!

I've uploaded them now. I don't have to create another pull request right? I'm new to git.

**Comment by elrumo** [comment]
You don't this is fine, thanks! Merging now

**Comment by Leavever** [comment]
Got it. Thanks.

**Pull request merged**
