### PR TITLE
Add 9 new icons

### PR DESCRIPTION
**Pull request by loukjltd**
Hi there,

It's my first time to use GitHub so it may cause some problems. 

The icons includes: ACDSee Photo Studio 6, App Cleaner & Uninstaller, EasyConnect, IT Home, NetEase Mail Master, NetEase Music, Snipaste, XMind and YouDao Dictionary. 9 new icons in total. My commits info were wrong by mistakes.

Please let me know it I can improve some. And I have submitted an issue to submit my new icon, cause I was not sure at that time. So, just close it if everything goes fine in the pull request.

Thanks!

### CODE REVIEW

**Comment by loukjltd** [comment]
Hi there, here're another 9 icons. I believe that I have uploaded them to the right place. Here is the preview for all 18 icons. Thanks!
Snipaste_2020-10-22_20-08-03

**Comment by loukjltd** [comment]
Hi, uh... is there any problem that I have made? Because it seems that it has been a few days since I made the pull request.

**Comment by elrumo** [comment]
I've been working on building an alternative way of submitng new icons directly from the site, so people not used to GitHub can also contribute to the project. That's been taking most of my time, that's why I haven't been as active with pull requests. I'll merge yours now

**Comment by loukjltd** [comment]
> I've been working on building an alternative way of submitting new icons directly from the site, so people not used to GitHub can also contribute to the project. That's been taking most of my time, that's why I haven't been as active with pull requests. I'll merge yours now, and thanks for the icons!!

Oh, thank you anyway.  I hope you will find a better way for users to submit their own icons in the future.  Of course, through this icon submission, I have learned how to use GitHub now haha :)

**Pull request merged**
