### PR TITLE
Added 23 Icons - High Res, Low Res, & .icns

### PR DESCRIPTION
**Pull request by KiwiBlueSpring**
**Added:**
Adobe_Substance_Painter,
Apple_Remote_Desktop,
Archicad_23,
Big_Sur,
Boom_2,
Boom_3D,
Class_Timetable,
Cities_Skylines,
Copied,
Copied_Alt,
EarthX,
House_Flipper,
House_Flipper_Alt,
Magnet_2,
Magnet_Alt_2,
NordVPN_2,
NordVPN_Alt_2,
NordVPN_IKE,
NordVPN_IKE_Alt,
Touch_Bar_Piano,
Touch_Bar_Piano_Alt,
Unigine_Valley,
Untitled_Goose_Game,

### CODE REVIEW

**Comment by elrumo** [comment]
Did you make them? If not, could you share a link to whoever made them so we can credit them? Thanks!!

**Comment by KiwiBlueSpring** [comment]
> Did you make them? If not, could you share a link to whoever made them so we can credit them? Thanks!!

Yes, I did make these myself. I can attach my original Sketch file if needed for proof?

**Comment by elrumo** [comment]
> 
> Yes, I did make these myself. I can attach my original Sketch file if needed for proof?

That's awesome! No need, I believe you.

**Comment by KiwiBlueSpring** [comment]
> > Yes, I did make these myself. I can attach my original Sketch file if needed for proof?
> 
> That's awesome! No need, I believe you.

Ah great! Thanks. :)

**Pull request merged**
