### PR TITLE
Added AdBlock, checkra1n, Displaperture, Edison Mail, GIMP, Origin alt, Pac-Bar, and The Sims 4

### PR DESCRIPTION
**Pull request by ThePotatoKing55**

### CODE REVIEW

**Comment by ThePotatoKing55** [comment]
Added Edison Mail

**Comment by Ovennell** [comment]
Don't forget png files "hi-res" and "low-res" folder.

**Comment by ThePotatoKing55** [comment]
Added the PNGs (and fixed a few issues with the icns files I uploaded)

**Comment by elrumo** [comment]
I've just noticed the low res icons are 72x72, for next time, could you make sure they are 200x200? Don't worry about this ones, I've already fixed them myself.
 It's just so they don't look pixelated on the website, thanks!

**Comment by ThePotatoKing55** [comment]
Thanks! I just saw that some of the other low-res icons were the same size so I figured that was the standard.

**Pull request merged**
