### PR TITLE
Added AirTable icons

### PR DESCRIPTION
**Pull request by alessiobulfaro**
Added AirTable icon.

### CODE REVIEW

**Comment by elrumo** [comment]
Looks great, but could you please add the low res (256px) and high res .pngs please? Or else the preview won't display on the website. Thanks!

**Comment by alessiobulfaro** [comment]
Ok, I've clone my fork repo on my machine. Commit done, but when I'm trying to push to the master brach, git gives me an error.
 
"Pushing to https://github.com/alessiobulfaro/macOS_Big_Sur_icons_replacements.git
ERROR: Authentication error: Authentication required: You must have push access to verify locks
error: failed to push some refs to 'https://github.com/alessiobulfaro/macOS_Big_Sur_icons_replacements.git'" 
**This is from SourceTree.** 

"This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.
error: failed to push some refs to 'https://alessiobulfaro@github.com/alessiobulfaro/macOS_Big_Sur_icons_replacements.git'"
**This is from Terminal**

**Comment by elrumo** [comment]
I think it might be because when I created the repo I enabled Git LFS to host a big .sketch file, but I've deleted it since so it doesn't need LFS anymore but I forgot to disable it. As a short term solution you could try installing LFS from [here](https://git-lfs.github.com). I'll make sure to disable it in the future.

**Comment by alessiobulfaro** [comment]
Tried but not work.

Inviato da iPad

**Comment by elrumo** [comment]
Hmm, that's strane. Don't worry about it then, I'll merge and add it myself.

**Pull request merged**
