### PR TITLE
IntelliJ_WebStorm Resized and Add New Icons

### PR DESCRIPTION
**Pull request by loukjltd**
I found that the exist IntelliJ_WebStorm Icon is bigger than the normal size. So, I resized it that will look as normal one. I made this pull request so I hope it can replace the old one. Files that contain an icns file, a high-res png file and a low-res png file. 

Sorry because previous name and pull request was wrong, so I made some extra commits. Now everything should work fine.

Thanks!

### CODE REVIEW

**Comment by loukjltd** [comment]
By the way, I have added another 5 new icons. Just merge them together I guess. Is everything OK? Let me know if something not good happened.

New icons list: Screencast, Tencent_Meeting, Tencent_Class, Tencent_Cloud, Xiaomi_Cloud.

All icns files, low & high res png have uploaded. The icns.txt have been updated.

**Comment by loukjltd** [comment]
Another 2 Icons coming, they're ScreenToLayers & VideoScan.

**Comment by loukjltd** [comment]
Another 7 new icons again. XD

**Comment by loukjltd** [comment]
Here, now 18 icons in total.

**Comment by elrumo** [comment]
Awesome, thanks for the icons!! Merging now :)

**Comment by loukjltd** [comment]
> Awesome, thanks for the icons!! Merging now :)

Thank you! 😄

**Pull request merged**
